- name: Docker configure in Ec2 Machine
  hosts: all
  become : true
  connection: ssh
  tasks:
  - name: updating the New Ec2 Machine 
    command: sudo apt update -y
    
  - name: Start Docker service
    command: service docker start
    become: yes
    become_user: root

  - name: Deploy the Image and Run as Container
    command: docker run -itd -p 8084:8081 rahultyadav/bankingproject:2.0    
